name: Build 'cu124-slim'

on:
  workflow_dispatch: # Can be manually triggered
  schedule: # Runs on every Monday, 07:00 UTC
    - cron: '0 7 * * 1'
  push:
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!cu124-slim/Dockerfile'
      - '!cu124-slim/builder-scripts/**'
      - '!cu124-slim/runner-scripts/**'
      - '!.github/workflows/build-cu124-slim.yml'

jobs:
  build-publish-cu124-slim:
    environment: Publish to GHCR
    runs-on: ubuntu-latest
    steps:
      -
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      -
        name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-android: 'true'
      -
        name: Git checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push 'cu124-slim'
        uses: docker/build-push-action@v6
        with:
          context: ./cu124-slim
          file: ./cu124-slim/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/comfyui-boot:cu124-slim
            ghcr.io/${{ github.repository_owner }}/comfyui-boot:cu124-slim-${{ steps.date.outputs.date }}
          push: true
